# Generated by Django 4.0.5 on 2022-06-29 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('joo_test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimg',
            name='post',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='joo_test.post'),
        ),
    ]
