# Generated by Django 4.0.5 on 2022-06-29 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joo_test', '0002_alter_postimg_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
