# Generated by Django 3.2.13 on 2022-07-04 07:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('joo_test', '0003_alter_post_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savepost',
            name='save_user',
        ),
        migrations.AddField(
            model_name='savepost',
            name='save_user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
