# Generated by Django 3.2.13 on 2022-07-04 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('joo_test', '0004_auto_20220704_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savepost',
            name='save_user',
        ),
        migrations.AddField(
            model_name='savepost',
            name='save_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
