# Generated by Django 3.2.13 on 2022-07-03 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('won_test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='like_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
