# Generated by Django 3.2.13 on 2022-07-04 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('won_test', '0002_alter_like_like_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='like_post',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='like_user',
            new_name='user',
        ),
    ]
