# Generated by Django 4.0.5 on 2022-07-01 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('joo_test', '0003_alter_post_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=128, verbose_name='댓글')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='생성 날짜')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='joo_test.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'comments',
            },
        ),
    ]
