# Generated by Django 4.0.5 on 2022-07-02 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment_test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성 날짜'),
        ),
    ]
